from typing import List
from schemas import AnalysisReport, Event, ReportRow

def generate_final_report(rows: List[ReportRow]) -> AnalysisReport:
    """
    Aggregates the rows and adds the disclaimer.
    """
    
    disclaimer = (
        "DISCLAIMER: This report is generated by an AI system (Sakshya AI) for preliminary analysis only. "
        "It does NOT constitute legal advice. Advs. must verify all citations and contradictions with original case records. "
        "The system does not assess the truthfulness of any statement."
    )
    
    return AnalysisReport(
        rows=rows,
        disclaimer=disclaimer
    )
