from typing import List, Dict
from schemas import AnalysisReport, Event, ReportRow

def group_and_prioritize_rows(rows: List[ReportRow]) -> List[ReportRow]:
    """
    Objective 2: Group Omissions.
    Objective 3: Prioritize Output (Max 2 Critical, 2 Material, 1 Minor).
    """
    # 1. Grouping Logic (Simplified for MVP)
    # We group rows that have same classification, severity, and similar explanation keywords?
    # Actually, let's group by Classification + Severity + (Context check via simple heuristic)
    
    # Pass-through for now as robust semantic grouping requires keeping source event Refs, which ReportRow loses partially.
    # However, we can perform suppression based on limits.
    
    criticals = [r for r in rows if r.severity == "Critical"]
    materials = [r for r in rows if r.severity == "Material"]
    minors = [r for r in rows if r.severity == "Minor"]
    others = [r for r in rows if r.severity not in ["Critical", "Material", "Minor"]] # e.g. "None" / "consistent"
    
    # 2. Prioritization Limits
    # Max 2 Critical, 2 Material, 1 Minor
    final_rows = []
    final_rows.extend(criticals[:2])
    final_rows.extend(materials[:2])
    final_rows.extend(minors[:1])
    
    # Add back any "other" important ones? usually we filter "consistent" out in main.py.
    
    return final_rows

def generate_final_report(rows: List[ReportRow]) -> AnalysisReport:
    """
    Aggregates the rows and adds the disclaimer.
    """
    
    # Apply Post-Processing
    processed_rows = group_and_prioritize_rows(rows)
    
    disclaimer = (
        "DISCLAIMER: This report is generated by an AI system (Sakshya AI) for preliminary analysis only. "
        "It does NOT constitute legal advice. Advs. must verify all citations and contradictions with original case records. "
        "The system does not assess the truthfulness of any statement."
    )
    
    return AnalysisReport(
        rows=processed_rows,
        disclaimer=disclaimer
    )

